# Base values
TOKEN=""
TERMINAL_ID=""
TARGET="https://fsv.demo.stellair.fr/"
API_VERSION="fsv/1.40.14/"
CLIENT_ID=""
CLIENT_SECRET=""

# API definitions
API_LIRE_CONFIG=$TARGET$API_VERSION"ssv/LireConfig"
API_LIRE_DATE_LECTEUR=$TARGET$API_VERSION"ssv/LireDateLecteur"
API_LIRE_CARTE_PS=$TARGET$API_VERSION"ssv/LireCartePS"
API_LIRE_DROITS_VITALE=$TARGET$API_VERSION"ssv/LireDroitsVitale"